### ISSUE TITLE
code

### ISSUE THREAD

**Issue by iPowerLife** [hldh214/lok_bot#14]
what?
2022-02-25 10:02:12.010 | WARNING  | lokbot.farmer:building_farmer_thread:294 - building_farmer: full_task, quit

![image](https://user-images.githubusercontent.com/99628430/155640090-b7081535-c81d-4bb9-94e0-018d4b28d74b.png)

**Comment by iPowerLife** [comment]
and tell me more, does the bot swing up to level 10 and that's it? will he stop then?

**Comment by hldh214** [comment]
😅 There are two threads for building farming
One is the default silver hammer worker queue
Another is the paid golden hammer worker queue
And this `full_task` warning was thrown when that account doesn't have the golden one
Just chill and ignore it, or you can fetch this commit 479c3be91cffd8b8215a87fa8494e411ef2527b0
Which added a detect for it and smartly choice whether to start the golden thread.

**Comment by hldh214** [comment]
> and tell me more, does the bot swing up to level 10 and that's it? will he stop then?

It's non-stop until there are some exception raised or user manually stop it.

**Comment by iPowerLife** [comment]
> 😅Существует два потока для создания фермы . Один — это рабочая очередь серебряного молота по умолчанию. Другой — платная рабочая очередь золотого молота. И это предупреждение было выдано, когда в этой учетной `full_task`записи нет золотого. [479c3be](https://github.com/hldh214/lok_bot/commit/479c3be91cffd8b8215a87fa8494e411ef2527b0) Который добавил для него детект и умный выбор запускать ли золотой поток.[](https://github.com/hldh214/lok_bot/commit/479c3be91cffd8b8215a87fa8494e411ef2527b0)

does it turn out to be anything terrible? how will the building be built, will it continue to work?

**Comment by iPowerLife** [comment]
> > и подскажите еще, бот качается до 10 уровня и все? он тогда остановится?
> 
> Это безостановочно, пока не возникнет какое-то исключение или пользователь не остановит его вручную.

а где то можешь добавить команду, чтобы при достижении 10 уровня замка, он дальше не качался?

**Comment by hldh214** [comment]
> > 😅Существует два потока для создания фермы . Один — это рабочая очередь серебряного молота по умолчанию. Другой — платная рабочая очередь золотого молота. И это предупреждение было выдано, когда в этой учетной `full_task`записи нет золотого. [479c3be](https://github.com/hldh214/lok_bot/commit/479c3be91cffd8b8215a87fa8494e411ef2527b0) Который добавил для него детект и умный выбор запускать ли золотой поток.
> 
> does it turn out to be anything terrible? how will the building be built, will it continue to work?

AFAIK, no, `full_task` is just that thread exited, other functions are still working as normal

**Comment by iPowerLife** [comment]
it would just be great if you could set parameters for each building, to what level to upgrade it, and so on, for example, so that the castle does not swing above level 10 or above 15. The resource storage is similarly not higher than level 4-8.

**Comment by hldh214** [comment]
> 

hmm, that's interesting feature, may I ask why we need this?

**Comment by iPowerLife** [comment]
And yet, I would modernize the code so that there is not a lot of code of extra values ​​​​in the console. for example, to just have a text - the building was built. resource collected. the new skill is learned and so on, otherwise now there are a lot of letters and numbers hahaha)

**Comment by iPowerLife** [comment]
> > 
> 
> хм, это интересная функция, могу я спросить, зачем нам это нужно?

so that I can swing up to level 10 and be able to safely jump to another continent. And also, to swing the account up to level 10 and after that, so that he only makes all sorts of troops and studies and collects loot. And it will also be convenient to rob this castle.

**Comment by hldh214** [comment]
> > > 
> > 
> > 
> > хм, это интересная функция, могу я спросить, зачем нам это нужно?
> 
> so that I can swing up to level 10 and be able to safely jump to another continent. And also, to swing the account up to level 10 and after that, so that he only makes all sorts of troops and studies and collects loot. And it will also be convenient to rob this castle.

That's a good idea. Can you provide your recommend of these configs for a better farming setting?

e.g. 
castle <= 10, 
storage <=8, 
hall_of_alliance <=2, 
...

**Comment by iPowerLife** [comment]
> > > > 
> > > 
> > > 
> > > хм, это интересная функция, могу я спросить, зачем нам это нужно?
> > 
> > 
> > чтобы я мог качать до 10 уровня и иметь возможность безопасно прыгать на другой континент. А еще, качать аккаунт до 10 уровня и после, чтобы он только делал всякие войска и изучал и собирал бабло. И грабить этот замок тоже будет удобно.
> 
> Это хорошая идея. Можете ли вы порекомендовать эти конфигурации для лучшей настройки фарма?
> 
> например , замок <= 10, хранилище <= 8, зал_альянса <= 2, ...

I need to see what level of storage is needed for level 10 of the castle and for level 15, I don’t remember exactly.

**Comment by iPowerLife** [comment]
it would also be great, for example, in terms of resources, to set how many mines to build for stone, grain, and so on. Let's say I want one castle level 10, where there will be only stone mining. And another castle where there will be gold and so on

**Comment by hldh214** [comment]
> it would also be great, for example, in terms of resources, to set how many mines to build for stone, grain, and so on. Let's say I want one castle level 10, where there will be only stone mining. And another castle where there will be gold and so on

Only one type of resources mining? Will it cause the other three resources to be insufficient when upgrading buildings?

**Comment by iPowerLife** [comment]
> > также было бы здорово, например, по ресурсам задать, сколько шахт строить для камня, зерна и так далее. Допустим, я хочу один замок 10 уровня, где будет только добыча камня. И еще один замок, где будет золото и так далее
> 
> Только один тип добычи ресурсов? Приведет ли это к тому, что трех других ресурсов будет недостаточно при обновлении зданий?


although yes, it makes no sense, but think about the level) so that the castle does not swing above level 10) so that only resources are collected and that's it.

**Comment by iPowerLife** [comment]
and what about a beautiful interface? to make it prettier?

**Comment by iPowerLife** [comment]
because a lot of beginners can't use it. And so you can make everything crooked and sell the finished product.

**Comment by hldh214** [comment]
> because a lot of beginners can't use it. And so you can make everything crooked and sell the finished product.

🤔Currently there is no plan to do UI-related improve. At least I'm not interested in.
Because this bot still have dozens of bugs, some of them even let your account get banned.
And another reason, which I think is the more people using this bot, the more chance we will get noticed by this game's GM, and that will make us harder to continue.

**Comment by mohsenyzd10** [comment]
> > > > 
> > > 
> > > 
> > > хм, это интересная функция, могу я спросить, зачем нам это нужно?
> > 
> > 
> > so that I can swing up to level 10 and be able to safely jump to another continent. And also, to swing the account up to level 10 and after that, so that he only makes all sorts of troops and studies and collects loot. And it will also be convenient to rob this castle.
> 
> That's a good idea. Can you provide your recommend of these configs for a better farming setting?
> 
> e.g. castle <= 10, storage <=8, hall_of_alliance <=2, ...

It's good idea , if we have option to stop upgrading castle upper than 10 and bot just upgrade other building , research ,farming , opening chest

**Comment by iPowerLife** [comment]
Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/app/lokbot/client.py", line 112, in _solve_captcha
    if not self.captcha_solver.solve(get_picture_base64_func, captcha_confirm_func):
AttributeError: 'NoneType' object has no attribute 'solve'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/lokbot/__main__.py", line 5, in <module>
    fire.Fire(main)
  File "/app/.venv/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/app/.venv/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/app/.venv/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/app/lokbot/app.py", line 24, in main
    farmer = LokFarmer(token, captcha_solver_config)
  File "/app/lokbot/farmer.py", line 19, in __init__
    self.kingdom_enter = self.api.kingdom_enter()
  File "/app/lokbot/client.py", line 186, in kingdom_enter
    self._solve_captcha()
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 361, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f0e07fa4910 state=finished raised AttributeError>]
PS C:\Users\PowerLife>


wtf

**Comment by hldh214** [comment]
> Traceback (most recent call last): File "/app/.venv/lib/python3.10/site-packages/tenacity/**init**.py", line 407, in **call** result = fn(*args, **kwargs) File "/app/lokbot/client.py", line 112, in _solve_captcha if not self.captcha_solver.solve(get_picture_base64_func, captcha_confirm_func): AttributeError: 'NoneType' object has no attribute 'solve'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/app/lokbot/**main**.py", line 5, in fire.Fire(main) File "/app/.venv/lib/python3.10/site-packages/fire/core.py", line 141, in Fire component_trace = _Fire(component, args, parsed_flag_args, context, name) File "/app/.venv/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire component, remaining_args = _CallAndUpdateTrace( File "/app/.venv/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace component = fn(*varargs, **kwargs) File "/app/lokbot/app.py", line 24, in main farmer = LokFarmer(token, captcha_solver_config) File "/app/lokbot/farmer.py", line 19, in **init** self.kingdom_enter = self.api.kingdom_enter() File "/app/lokbot/client.py", line 186, in kingdom_enter self._solve_captcha() File "/app/.venv/lib/python3.10/site-packages/tenacity/**init**.py", line 324, in wrapped_f return self(f, *args, **kw) File "/app/.venv/lib/python3.10/site-packages/tenacity/**init**.py", line 404, in **call** do = self.iter(retry_state=retry_state) File "/app/.venv/lib/python3.10/site-packages/tenacity/**init**.py", line 361, in iter raise retry_exc from fut.exception() tenacity.RetryError: RetryError[<Future at 0x7f0e07fa4910 state=finished raised AttributeError>] PS C:\Users\PowerLife>
> 
> wtf

Seems like the issue you met 2 days ago, have you fetched the latest code?
https://github.com/hldh214/lok_bot/issues/7#issuecomment-1049684273

**Comment by mohsenyzd10** [comment]
![image](https://user-images.githubusercontent.com/91246296/155833320-ad3e96fb-2c25-4449-8182-bdca45cd3a7c.png)

![image](https://user-images.githubusercontent.com/91246296/155833353-765639f3-470c-4d07-93f5-cca537c3fae2.png)

I also get the error and my account sign out from game because of duplicate signing warning

**Comment by hldh214** [comment]
> ![image](https://user-images.githubusercontent.com/91246296/155833320-ad3e96fb-2c25-4449-8182-bdca45cd3a7c.png)
> 
> ![image](https://user-images.githubusercontent.com/91246296/155833353-765639f3-470c-4d07-93f5-cca537c3fae2.png)
> 
> I also get the error and my account sign out from game because of duplicate signing warning and my account banned
> 
> the pervious code worked for me fine , but seems new changes make bot crash

Sorry to hear that, maybe they are trying to detect device info which I hard-coded here, you can try modify this and see if still get banned? https://github.com/hldh214/lok_bot/blob/e8b2fd5b61e6a1c49751fcd90518dc688b9706d5/lokbot/farmer.py#L20-L27

**Comment by iPowerLife** [comment]
> > ![image](https://user-images.githubusercontent.com/91246296/155833320-ad3e96fb-2c25-4449-8182-bdca45cd3a7c.png)
> > ![image](https://user-images.githubusercontent.com/91246296/155833353-765639f3-470c-4d07-93f5-cca537c3fae2.png)
> > I also get the error and my account sign out from game because of duplicate signing warning and my account banned
> > the pervious code worked for me fine , but seems new changes make bot crash
> 
> Sorry to hear that, maybe they are trying to detect device info which I hard-coded here, you can try modify this and see if still get banned?
> 
> https://github.com/hldh214/lok_bot/blob/e8b2fd5b61e6a1c49751fcd90518dc688b9706d5/lokbot/farmer.py#L20-L27

https://github.com/hldh214/lok_bot/issues/14#issuecomment-1051931207

**Comment by mohsenyzd10** [comment]
do you have any solution for my problem, every time I closed the game tab of browser, bot also stop working

**Comment by hldh214** [comment]
> do you have any solution for my problem, every time I closed the game tab of browser, bot also stop working
> 
> and also, if I want bot stop upgrade buildings and just do other things , which part of code I should change to comment

Q1: Currently no, because I cannot reproduce it.
Q2: 
https://github.com/hldh214/lok_bot/blob/8d5fc10024bfb7be38d06aed8c8558f50b29734c/lokbot/app.py#L40-L41

**Comment by mohsenyzd10** [comment]
> 

I stop upgrading building when my castle reach lvl 10 , the problem is researching also stop after all research items reach lvl 2 , 
as you can see on below (I upgrade some research by myself but majority still in lvl2 and bot givs 'no research to do' )
is there any solution ? 
`2022-03-10 22:17:34.316 | DEBUG    | lokbot.client:post:72 - {"url": "kingdom/arcademy/research/list", "data": {}, "elapsed": 0.382487, "res": {"result": true, "researches": [{"_id": "62173bd77918d722cb559536", "code": 30102001, "level": 2}, {"_id": "62173f7e7a2a2216e19f0688", "code": 30102002, "level": 2}, {"_id": "621740110c1c1b68272cf54a", "code": 30102003, "level": 2}, {"_id": "621740d9f629ec136b48f0bb", "code": 30101001, "level": 2}, {"_id": "6217461a9a25fc153b3000da", "code": 30101002, "level": 2}, {"_id": "621746df7a4cf9160879556b", "code": 30101003, "level": 2}, {"_id": "62179b48199cb0238c0c2efc", "code": 30102004, "level": 2}, {"_id": "62179fb15297c80614679cff", "code": 30101004, "level": 2}, {"_id": "6217a33ef7706f0f44c21fd2", "code": 30101005, "level": 2}, {"_id": "6217a6df3455bd15544dc8a4", "code": 30101006, "level": 2}, {"_id": "62189733151f8d0ee9b9da1b", "code": 30102005, "level": 4}, {"_id": "6218a13ff3a685328ed63bf6", "code": 30102006, "level": 5}, {"_id": "6218a9b9d746871a54b0757a", "code": 30102007, "level": 5}, {"_id": "6218b061a43e071af65bb3db", "code": 30101007, "level": 2}, {"_id": "6218c1d85504080f3df8ff8f", "code": 30101008, "level": 2}, {"_id": "6218e203cdd3c61b3569f067", "code": 30101009, "level": 2}, {"_id": "6220ed320025e121c3f884e9", "code": 30101012, "level": 2}, {"_id": "622286165bf071258b93c1de", "code": 30102008, "level": 3}, {"_id": "62229393ff130c107d3593a2", "code": 30101010, "level": 2}, {"_id": "6222a843c116c82aae3e1a87", "code": 30102009, "level": 2}, {"_id": "6222c09379e8df2b5c8d5b63", "code": 30102010, "level": 2}, {"_id": "6222d8e2d00b7314cffe70d2", "code": 30102011, "level": 2}, {"_id": "6222ed8cf7330115704b6005", "code": 30101011, "level": 2}, {"_id": "62230979a11d931012b05733", "code": 30101013, "level": 4}, {"_id": "62235d72bf1704116c31b50d", "code": 30101016, "level": 1}, {"_id": "62245e236a5e5d0fc80871da", "code": 30101014, "level": 1}, {"_id": "6225e89f929aae248f8ce2eb", "code": 30101015, "level": 1}]}}
2022-03-10 22:17:34.323 | INFO     | lokbot.farmer:academy_farmer_thread:501 - start researching category: production
2022-03-10 22:17:34.329 | INFO     | lokbot.farmer:academy_farmer_thread:501 - start researching category: battle
2022-03-10 22:17:34.334 | INFO     | lokbot.farmer:academy_farmer_thread:501 - start researching category: advanced
2022-03-10 22:17:34.340 | INFO     | lokbot.farmer:academy_farmer_thread:525 - academy_farmer: no research to do, sleep for 2h`

**Comment by mohsenyzd10** [comment]
> 

harvest function is not working for me, In recent versions of bot

**Comment by hldh214** [comment]
> > 
> 
> harvest function is not working for me, In recent versions of bot

Any output or log please?

**Comment by mohsenyzd10** [comment]
this is part of log that I choose, I think the problem is the capacity storage of buildings are very low and it will be full after 1 hours but log show us that the time between last harvest and current is very long, 
 

`2022-03-21 20:56:42.099 | DEBUG    | lokbot.client:post:73 - {"url": "kingdom/resource/harvest", "data": {"position": 110}, "elapsed": 1.244228, "res": {"result": true, "deltaResource": [0, 28551], "harvested": [{"position": 104, "harvested": 9517, "lastHarvested": "2022-03-22T03:56:40.910Z"}, {"position": 110, "harvested": 9517, "lastHarvested": "2022-03-22T03:56:40.770Z"}, {"position": 117, "harvested": 9517, "lastHarvested": "2022-03-22T03:56:40.554Z"}], "resources": [2324409, 3657420, 1788596, 166357]}}
2022-03-21 20:56:42.106 | INFO     | lokbot.farmer:_request_callback:184 - resources updated: [2324409, 3657420, 1788596, 166357]
2022-03-21 20:56:45.584 | DEBUG    | lokbot.client:post:73 - {"url": "kingdom/resource/harvest", "data": {"position": 107}, "elapsed": 0.450123, "res": {"result": true, "deltaResource": [2, 28104], "harvested": [{"position": 103, "harvested": 9368, "lastHarvested": "2022-03-22T03:56:40.619Z"}, {"position": 107, "harvested": 9368, "lastHarvested": "2022-03-22T03:56:40.427Z"}, {"position": 111, "harvested": 9368, "lastHarvested": "2022-03-22T03:56:40.589Z"}], "resources": [2324409, 3657420, 1816700, 166357]}}
2022-03-21 20:56:45.584 | INFO     | lokbot.farmer:_request_callback:184 - resources updated: [2324409, 3657420, 1816700, 166357]
2022-03-21 20:56:50.279 | DEBUG    | lokbot.client:post:73 - {"url": "kingdom/resource/harvest", "data": {"position": 118}, "elapsed": 0.657161, "res": {"result": true, "deltaResource": [1, 37771], "harvested": [{"position": 101, "harvested": 9443, "lastHarvested": "2022-03-22T03:56:40.878Z"}, {"position": 106, "harvested": 9443, "lastHarvested": "2022-03-22T03:56:40.890Z"}, {"position": 109, "harvested": 9442, "lastHarvested": "2022-03-22T03:56:40.538Z"}, {"position": 118, "harvested": 9443, "lastHarvested": "2022-03-22T03:56:40.739Z"}], "resources": [2324409, 3695191, 1816700, 166357]}}
2022-03-21 20:56:50.279 | INFO     | lokbot.farmer:_request_callback:184 - resources updated: [2324409, 3695191, 1816700, 166357]
2022-03-21 20:56:54.732 | DEBUG    | lokbot.client:post:73 - {"url": "kingdom/resource/harvest", "data": {"position": 108}, "elapsed": 0.420132, "res": {"result": true, "deltaResource": [3, 27436], "harvested": [{"position": 102, "harvested": 9145, "lastHarvested": "2022-03-22T03:56:40.792Z"}, {"position": 108, "harvested": 9146, "lastHarvested": "2022-03-22T03:56:40.844Z"}, {"position": 116, "harvested": 9145, "lastHarvested": "2022-03-22T03:56:40.497Z"}], "resources": [2324409, 3695191, 1816700, 193793]}}
2022-03-21 20:56:54.732 | INFO     | lokbot.farmer:_request_callback:184 - resources updated: [2324409, 3695191, 1816700, 193793]`

**Comment by hldh214** [comment]
> this is part of log that I choose, I think the problem is the capacity storage of buildings are very low and it will be full after 1 hours but log show us that the time between last harvest and current is very long,
> 
> `2022-03-21 20:56:42.099 | DEBUG | lokbot.client:post:73 - {"url": "kingdom/resource/harvest", "data": {"position": 110}, "elapsed": 1.244228, "res": {"result": true, "deltaResource": [0, 28551], "harvested": [{"position": 104, "harvested": 9517, "lastHarvested": "2022-03-22T03:56:40.910Z"}, {"position": 110, "harvested": 9517, "lastHarvested": "2022-03-22T03:56:40.770Z"}, {"position": 117, "harvested": 9517, "lastHarvested": "2022-03-22T03:56:40.554Z"}], "resources": [2324409, 3657420, 1788596, 166357]}} 2022-03-21 20:56:42.106 | INFO | lokbot.farmer:_request_callback:184 - resources updated: [2324409, 3657420, 1788596, 166357] 2022-03-21 20:56:45.584 | DEBUG | lokbot.client:post:73 - {"url": "kingdom/resource/harvest", "data": {"position": 107}, "elapsed": 0.450123, "res": {"result": true, "deltaResource": [2, 28104], "harvested": [{"position": 103, "harvested": 9368, "lastHarvested": "2022-03-22T03:56:40.619Z"}, {"position": 107, "harvested": 9368, "lastHarvested": "2022-03-22T03:56:40.427Z"}, {"position": 111, "harvested": 9368, "lastHarvested": "2022-03-22T03:56:40.589Z"}], "resources": [2324409, 3657420, 1816700, 166357]}} 2022-03-21 20:56:45.584 | INFO | lokbot.farmer:_request_callback:184 - resources updated: [2324409, 3657420, 1816700, 166357] 2022-03-21 20:56:50.279 | DEBUG | lokbot.client:post:73 - {"url": "kingdom/resource/harvest", "data": {"position": 118}, "elapsed": 0.657161, "res": {"result": true, "deltaResource": [1, 37771], "harvested": [{"position": 101, "harvested": 9443, "lastHarvested": "2022-03-22T03:56:40.878Z"}, {"position": 106, "harvested": 9443, "lastHarvested": "2022-03-22T03:56:40.890Z"}, {"position": 109, "harvested": 9442, "lastHarvested": "2022-03-22T03:56:40.538Z"}, {"position": 118, "harvested": 9443, "lastHarvested": "2022-03-22T03:56:40.739Z"}], "resources": [2324409, 3695191, 1816700, 166357]}} 2022-03-21 20:56:50.279 | INFO | lokbot.farmer:_request_callback:184 - resources updated: [2324409, 3695191, 1816700, 166357] 2022-03-21 20:56:54.732 | DEBUG | lokbot.client:post:73 - {"url": "kingdom/resource/harvest", "data": {"position": 108}, "elapsed": 0.420132, "res": {"result": true, "deltaResource": [3, 27436], "harvested": [{"position": 102, "harvested": 9145, "lastHarvested": "2022-03-22T03:56:40.792Z"}, {"position": 108, "harvested": 9146, "lastHarvested": "2022-03-22T03:56:40.844Z"}, {"position": 116, "harvested": 9145, "lastHarvested": "2022-03-22T03:56:40.497Z"}], "resources": [2324409, 3695191, 1816700, 193793]}} 2022-03-21 20:56:54.732 | INFO | lokbot.farmer:_request_callback:184 - resources updated: [2324409, 3695191, 1816700, 193793]`

The latest commit (0ac13f352f385f36cb3d4bcd6e55b9be366e1cb3) add config support, which can manually define interval.
```json5
{
  "name": "harvester",
  "enabled": true,
  "interval": {  // in minutes
    // executes the job function every N minutes such that 60 <= N <= 120.
    "start": 60,   // random interval start
    "end": 120  // end
  }
}
```
