### ISSUE TITLE
march troop size and _is_march_limit_exceeded

### ISSUE THREAD

**Issue by mohsenyzd10** [hldh214/lok_bot#25]
it's seems bot march random amount of troops 
also my troop dispatch queue are 8 but bot just used at max 6  
![image](https://user-images.githubusercontent.com/91246296/161385339-1aaac57f-1257-4cbb-bbab-0d2bdeba5159.png)

**Comment by hldh214** [comment]
Full output log please.

**Comment by mohsenyzd10** [comment]
> Full output log please.

also this Kind of error

 2022-04-02 22:36:28.556 | DEBUG    | lokbot.client:post:73 - {"url": "field/march/start", "data": {"fromId": "6240ad24512e2c7d66f0c03d", "marchType": 1, "toLoc": [16, 848, 1043], "marchTroops": [{"code": 50100304, "amount": 201, "level": 0, "select": 0, "dead": 0, "wounded": 0, "seq": 0}, {"code": 50100303, "amount": 156743, "level": 0, "select": 0, "dead": 0, "wounded": 0, "seq": 0}, {"code": 50100103, "amount": 5939, "level": 0, "select": 0, "dead": 0, "wounded": 0, "seq": 0}]}, "elapsed": 0.582863, "res": {"result": false, "err": {"code": "exceed_march_size"}}}
Exception in thread Thread-871 (_handle_eio_message):
Traceback (most recent call last):
  File "C:\Users\myjaj\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\myjaj\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\socketio\client.py", line 621, in _handle_eio_message
    self._handle_event(pkt.namespace, pkt.id, pkt.data)
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\socketio\client.py", line 505, in _handle_event
    r = self._trigger_event(data[0], namespace, *data[1:])
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\socketio\client.py", line 555, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "D:\test\lok_bot\lokbot\farmer.py", line 544, in on_field_objects
    self._on_field_objects_gather(each_obj)
  File "D:\test\lok_bot\lokbot\farmer.py", line 437, in _on_field_objects_gather
    self._start_march(to_loc, march_troops, MARCH_TYPE_GATHER)
  File "D:\test\lok_bot\lokbot\farmer.py", line 353, in _start_march
    res = self.api.field_march_start({
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\tenacity\__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\tenacity\__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\tenacity\__init__.py", line 349, in iter
    return fut.result()
  File "C:\Users\myjaj\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\myjaj\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\tenacity\__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\ratelimit\decorators.py", line 80, in wrapper
    return func(*args, **kargs)
  File "D:\test\lok_bot\lokbot\client.py", line 520, in field_march_start
    return self.post('field/march/start', data)
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\tenacity\__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\tenacity\__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\tenacity\__init__.py", line 349, in iter
    return fut.result()
  File "C:\Users\myjaj\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\myjaj\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\tenacity\__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\tenacity\__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\tenacity\__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\tenacity\__init__.py", line 349, in iter
    return fut.result()
  File "C:\Users\myjaj\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\myjaj\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\tenacity\__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\tenacity\__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\tenacity\__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\tenacity\__init__.py", line 349, in iter
    return fut.result()
  File "C:\Users\myjaj\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\myjaj\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\tenacity\__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\tenacity\__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\tenacity\__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\tenacity\__init__.py", line 349, in iter
    return fut.result()
  File "C:\Users\myjaj\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\myjaj\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\tenacity\__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\myjaj\.virtualenvs\lok_bot-0WlCcbBG\lib\site-packages\ratelimit\decorators.py", line 80, in wrapper
    return func(*args, **kargs)
  File "D:\test\lok_bot\lokbot\client.py", line 101, in post
    raise OtherException(code)
lokbot.exceptions.OtherException: exceed_march_size

**Comment by mohsenyzd10** [comment]
![image](https://user-images.githubusercontent.com/91246296/161413160-13eb6cb3-105e-4920-97f5-812ccbbe6b17.png)

**Comment by mohsenyzd10** [comment]
> Full output log please.

![image](https://user-images.githubusercontent.com/91246296/161429218-93ceb8aa-9278-46b2-82d8-4d8535668351.png)

2022-04-03 05:10:15.774 | INFO     | lokbot.farmer:_prepare_march_troops:391 - distance: 282, object: {'_id': '62498d8a7a299d5e53881228', 'loc': [10, 674, 1324], 'level': 2, 'code': 20100105, 'param': {'value': 100}, 'state': 1, 'expired': '2022-04-04T18:23:13.067Z'}
2022-04-03 05:10:16.332 | DEBUG    | lokbot.client:post:73 - {"url": "field/march/start", "data": {"fromId": "62415803eff21179e059e2a2", "marchType": 1, "toLoc": [10, 674, 1324], "marchTroops": [{"code": 50100305, "amount": 101, "level": 0, "select": 0, "dead": 0, "wounded": 0, "seq": 0}, {"code": 50100304, "**amount": 254612,** "level": 0, "select": 0, "dead": 0, "wounded": 0, "seq": 0}]}, "elapsed": 0.518455, "res": {"result": true, "newTask": {"_id": "62498ea873b60e6d5412e0c5", "code": 2, "status": 1, "started": "2022-04-03T12:10:16.107Z", "expectedEnded": "2022-04-03T12:11:23.842Z", "time": 67.73554314537921, "param": {"fromId": "62415803eff21179e059e2a2", "fromLoc": [10, 903, 1161], "toLoc": [10, 674, 1324], "distance": 282, "marchType": 1, "moId": "62498ea873b60e6d5412e0c6"}}}}

**Comment by svenmanderscheid** [comment]
Did you change something in the code? 
When i am running the bot he isn't sending troops to farm at all. Or am i doing something wrong?

**Comment by hldh214** [comment]
> `"code": 50100304, "amount": 254612`

Is this `254612` your all troops or just a part of it?

**Comment by mohsenyzd10** [comment]
> > `"code": 50100304, "amount": 254612`
> 
> Is this `amount: 254612` your all troops under `code: 50100304 (I guess is T4 horse man)` or just a part of it?

it's part of my troops under code: 50100304 
I check this bug, bot always send one march with almost full march size ,

**Comment by hldh214** [comment]
Please try this commit 3c20fb733b41bc82705382163325beaa9e101926

**Comment by mohsenyzd10** [comment]
> Please try this commit [3c20fb7](https://github.com/hldh214/lok_bot/commit/3c20fb733b41bc82705382163325beaa9e101926)
i get this error:

09 18:06:02.268 | INFO     | lokbot.farmer:_prepare_march_troops:389 - distance: 229, object: {'_id': '625159f731d83a78b6e0c', 'loc': [10, 823, 1167], 'level': 2, 'code': 20100105, 'param': {'value': 100}, 'state': 1, 'expired': '2022-04-10T20:12:00.269Z'}

2022-04-
09 18:06:02.580 | DEBUG    | lokbot.client:post:73 - {"url": "field/march/start", "data": {"fromId": "6240ad24512e2c0c03d", "marchType": 1, "toLoc": [10, 823, 1167], "marchTroops": [{"code": 50100304, "amount": 101, "level": 0, "select": 0, "dead": 0, "wounded": 0, "seq": 0}, {"code": 50100303, "amount": 156743, "level": 0, "select": 0, "dead": 0, "wounded": 0, "seq": 0}, {"code": 50100203, "amount": 22895, "level": 0, "select": 0, "dead": 0, "wounded": 0, "seq": 0}, {"code": 50100104, "amount": 97108, "level": 0, "select": 0, "dead": 0, "wounded": 0, "seq": 0}, {"code": 50100103, "amount": 5939, "level": 0, "select": 0, "dead": 0, "wounded": 0, "seq": 0}]}, "elapsed": 0.306482, "res": {"result": false, "err": {"code": "exceed_march_size"}}}

Exception in thread Thread-2503 (_handle_eio_message):

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner

    self.run()

  File "/usr/local/lib/python3.10/threading.py", line 946, in run

    self._target(*self._args, **self._kwargs)

  File "/app/.venv/lib/python3.10/site-packages/socketio/client.py", line 621, in _handle_eio_message

    self._handle_event(pkt.namespace, pkt.id, pkt.data)

  File "/app/.venv/lib/python3.10/site-packages/socketio/client.py", line 505, in _handle_event

    r = self._trigger_event(data[0], namespace, *data[1:])

  File "/app/.venv/lib/python3.10/site-packages/socketio/client.py", line 555, in _trigger_event

    return self.handlers[namespace][event](*args)

  File "/app/lokbot/farmer.py", line 539, in on_field_objects

    self._on_field_objects_gather(each_obj)

  File "/app/lokbot/farmer.py", line 432, in _on_field_objects_gather

    self._start_march(to_loc, march_troops, MARCH_TYPE_GATHER)

  File "/app/lokbot/farmer.py", line 351, in _start_march

    res = self.api.field_march_start({

  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 324, in wrapped_f

    return self(f, *args, **kw)

  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__

    do = self.iter(retry_state=retry_state)

  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 349, in iter

    return fut.result()

  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 439, in result

    return self.__get_result()

  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result

    raise self._exception

  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__

    result = fn(*args, **kwargs)

  File "/app/.venv/lib/python3.10/site-packages/ratelimit/decorators.py", line 80, in wrapper

    return func(*args, **kargs)

  File "/app/lokbot/client.py", line 520, in field_march_start

    return self.post('field/march/start', data)

  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 324, in wrapped_f

    return self(f, *args, **kw)

  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__

    do = self.iter(retry_state=retry_state)

  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 349, in iter

    return fut.result()

  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 439, in result

    return self.__get_result()

  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result

    raise self._exception

  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__

    result = fn(*args, **kwargs)

  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 324, in wrapped_f

    return self(f, *args, **kw)

  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__

    do = self.iter(retry_state=retry_state)

  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 349, in iter

    return fut.result()

  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 439, in result

    return self.__get_result()

  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result

    raise self._exception

  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__

    result = fn(*args, **kwargs)

  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 324, in wrapped_f

    return self(f, *args, **kw)

  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__

    do = self.iter(retry_state=retry_state)

  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 349, in iter

    return fut.result()

  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 439, in result

    return self.__get_result()

  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result

    raise self._exception

  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__

    result = fn(*args, **kwargs)

  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 324, in wrapped_f

    return self(f, *args, **kw)

  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__

    do = self.iter(retry_state=retry_state)

  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 349, in iter

    return fut.result()

  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 439, in result

    return self.__get_result()

  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result

    raise self._exception

  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__

    result = fn(*args, **kwargs)

  File "/app/.venv/lib/python3.10/site-packages/ratelimit/decorators.py", line 80, in wrapper

    return func(*args, **kargs)

  File "/app/lokbot/client.py", line 101, in post

    raise OtherException(code)

lokbot.exceptions.OtherException: exceed_march_size

**Comment by marcussb** [comment]
in new update the bot use all action point, where is the code for i change i dont find the commit for i change it

**Comment by svenmanderscheid** [comment]
Change the usable item code list in the enum.py

**Comment by some-say-something** [comment]
I have the same problem :(
