### ISSUE TITLE
Getting Error "UnicodeEncodeError: 'charmap' codec can't encode characters"

### ISSUE THREAD

**Issue by starrock2** [hldh214/lok_bot#38]
Hello,

I am getting below error, the code is not stopping..

--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 283-287: character maps to <undefined>
Call stack:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\engineio\client.py", line 669, in _read_loop_websocket

**Comment by hldh214** [comment]
Please try setting environment variable before running

```
# Use the UTF-8 mode on Windows
export PYTHONUTF8=1
```

**Comment by starrock2** [comment]
Working Fine now.

**Comment by diego0700** [comment]
i have python on environment variable but still not working 
![image](https://user-images.githubusercontent.com/104273655/165963433-1592904d-f720-42e8-be08-3ae18211627c.png)
