### ISSUE TITLE
Bot stops working after 1 min

### ISSUE THREAD

**Issue by Eddsss1** [hldh214/lok_bot#48]
I am getting the following errors after 1 minute of running the bot? How can I resolve this?

--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Andrej\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\Andrej\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2606' in position 1384: character maps to <undefined>
Call stack:
  File "C:\Users\Andrej\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\Andrej\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Andrej\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Andrej\.virtualenvs\lok-LPLZ91B9\lib\site-packages\engineio\client.py", line 669, in _read_loop_websocket
    self._receive_packet(pkt)
  File "C:\Users\Andrej\.virtualenvs\lok-LPLZ91B9\lib\site-packages\engineio\client.py", line 504, in _receive_packet
    self.logger.info(
Message: 'Received packet %s data %s'

**Comment by hldh214** [comment]
Please refer to https://github.com/hldh214/lok_bot/issues/38
