### ISSUE TITLE
I encountered this error. Please help me

### ISSUE THREAD

**Issue by caophongofficial** [hldh214/lok_bot#55]
(lok_bot-KUZYcncA) C:\Users\anhnongdan\Downloads\Compressed\lok_bot>python -m lokbot eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWFhMTdmYTk5YTBjMzBjYjgwN2VmN2IiLCJraW5nZG9tSWQiOiI2MWFhMTdmYTk5YTBjMzBjYjgwN2VmN2MiLCJ2ZXJzaW9uIjoxNDI2LCJ0aW1lIjoxNjUxOTQ1NzgzODU2LCJpYXQiOjE2NTE5NDU3ODMsImV4cCI6MTY1MjU1MDU4MywiaXNzIjoibm9kZ2FtZXMuY29tIiwic3ViIjoidXNlckluZm8ifQ.Y1TFpsVOflIjop6pr2aJWU1AzzHv6pHqx9YibfUoSd0
2022-05-08 00:59:28.312 | DEBUG    | lokbot.client:post:72 - {"url": "kingdom/enter", "data": {}, "elapsed": 1.386117, "res": {"result": false, "err": {"code": "no_auth"}}}
Traceback (most recent call last):
  File "C:\Users\anhnongdan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\anhnongdan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\anhnongdan\Downloads\Compressed\lok_bot\lokbot\__main__.py", line 5, in <module>
    fire.Fire(main)
  File "C:\Users\anhnongdan\.virtualenvs\lok_bot-KUZYcncA\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\anhnongdan\.virtualenvs\lok_bot-KUZYcncA\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\anhnongdan\.virtualenvs\lok_bot-KUZYcncA\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\anhnongdan\Downloads\Compressed\lok_bot\lokbot\app.py", line 65, in main
    farmer = LokFarmer(token, captcha_solver_config)
  File "C:\Users\anhnongdan\Downloads\Compressed\lok_bot\lokbot\farmer.py", line 73, in __init__
    self.kingdom_enter = self.api.kingdom_enter()
  File "C:\Users\anhnongdan\Downloads\Compressed\lok_bot\lokbot\client.py", line 270, in kingdom_enter
    res = self.post('kingdom/enter')
  File "C:\Users\anhnongdan\.virtualenvs\lok_bot-KUZYcncA\lib\site-packages\tenacity\__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\anhnongdan\.virtualenvs\lok_bot-KUZYcncA\lib\site-packages\tenacity\__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\anhnongdan\.virtualenvs\lok_bot-KUZYcncA\lib\site-packages\tenacity\__init__.py", line 349, in iter
    return fut.result()
  File "C:\Users\anhnongdan\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\anhnongdan\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\anhnongdan\.virtualenvs\lok_bot-KUZYcncA\lib\site-packages\tenacity\__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\anhnongdan\.virtualenvs\lok_bot-KUZYcncA\lib\site-packages\tenacity\__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\anhnongdan\.virtualenvs\lok_bot-KUZYcncA\lib\site-packages\tenacity\__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\anhnongdan\.virtualenvs\lok_bot-KUZYcncA\lib\site-packages\tenacity\__init__.py", line 349, in iter
    return fut.result()
  File "C:\Users\anhnongdan\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\anhnongdan\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\anhnongdan\.virtualenvs\lok_bot-KUZYcncA\lib\site-packages\tenacity\__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\anhnongdan\.virtualenvs\lok_bot-KUZYcncA\lib\site-packages\tenacity\__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\anhnongdan\.virtualenvs\lok_bot-KUZYcncA\lib\site-packages\tenacity\__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\anhnongdan\.virtualenvs\lok_bot-KUZYcncA\lib\site-packages\tenacity\__init__.py", line 349, in iter
    return fut.result()
  File "C:\Users\anhnongdan\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\anhnongdan\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\anhnongdan\.virtualenvs\lok_bot-KUZYcncA\lib\site-packages\tenacity\__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\anhnongdan\.virtualenvs\lok_bot-KUZYcncA\lib\site-packages\tenacity\__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\anhnongdan\.virtualenvs\lok_bot-KUZYcncA\lib\site-packages\tenacity\__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\anhnongdan\.virtualenvs\lok_bot-KUZYcncA\lib\site-packages\tenacity\__init__.py", line 349, in iter
    return fut.result()
  File "C:\Users\anhnongdan\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\anhnongdan\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\anhnongdan\.virtualenvs\lok_bot-KUZYcncA\lib\site-packages\tenacity\__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\anhnongdan\.virtualenvs\lok_bot-KUZYcncA\lib\site-packages\ratelimit\decorators.py", line 80, in wrapper
    return func(*args, **kargs)
  File "C:\Users\anhnongdan\Downloads\Compressed\lok_bot\lokbot\client.py", line 84, in post
    raise NoAuthException()
lokbot.exceptions.NoAuthException

**Comment by caophongofficial** [comment]
**I can't sync, can someone help me**


C:\Users\anhnongdan\Downloads\Compressed\lok_bot>pipenv sync
Installing dependencies from Pipfile.lock (fb38e8)...
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\anhnongdan\AppData\Roaming\Python\Python310\Scripts\pipenv.exe\__main__.py", line 7, in <module>
  File "C:\Users\anhnongdan\AppData\Roaming\Python\Python310\site-packages\pipenv\vendor\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\anhnongdan\AppData\Roaming\Python\Python310\site-packages\pipenv\cli\options.py", line 56, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "C:\Users\anhnongdan\AppData\Roaming\Python\Python310\site-packages\pipenv\vendor\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\anhnongdan\AppData\Roaming\Python\Python310\site-packages\pipenv\vendor\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\anhnongdan\AppData\Roaming\Python\Python310\site-packages\pipenv\vendor\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\anhnongdan\AppData\Roaming\Python\Python310\site-packages\pipenv\vendor\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\anhnongdan\AppData\Roaming\Python\Python310\site-packages\pipenv\vendor\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\anhnongdan\AppData\Roaming\Python\Python310\site-packages\pipenv\vendor\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\anhnongdan\AppData\Roaming\Python\Python310\site-packages\pipenv\vendor\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\anhnongdan\AppData\Roaming\Python\Python310\site-packages\pipenv\cli\command.py", line 671, in sync
    retcode = do_sync(
  File "C:\Users\anhnongdan\AppData\Roaming\Python\Python310\site-packages\pipenv\core.py", line 2973, in do_sync
    do_init(
  File "C:\Users\anhnongdan\AppData\Roaming\Python\Python310\site-packages\pipenv\core.py", line 1336, in do_init
    do_install_dependencies(
  File "C:\Users\anhnongdan\AppData\Roaming\Python\Python310\site-packages\pipenv\core.py", line 871, in do_install_dependencies
    batch_install(
  File "C:\Users\anhnongdan\AppData\Roaming\Python\Python310\site-packages\pipenv\core.py", line 729, in batch_install
    deps_to_install = [
  File "C:\Users\anhnongdan\AppData\Roaming\Python\Python310\site-packages\pipenv\core.py", line 730, in <listcomp>
    dep for dep in deps_to_install if not project.environment.is_satisfied(dep)
  File "C:\Users\anhnongdan\AppData\Roaming\Python\Python310\site-packages\pipenv\project.py", line 319, in environment
    self._environment = self.get_environment(allow_global=allow_global)
  File "C:\Users\anhnongdan\AppData\Roaming\Python\Python310\site-packages\pipenv\project.py", line 299, in get_environment
    environment = Environment(
  File "C:\Users\anhnongdan\AppData\Roaming\Python\Python310\site-packages\pipenv\environment.py", line 70, in __init__
    self._base_paths = self.get_paths()
  File "C:\Users\anhnongdan\AppData\Roaming\Python\Python310\site-packages\pipenv\environment.py", line 394, in get_paths
    c = subprocess_run(command)
  File "C:\Users\anhnongdan\AppData\Roaming\Python\Python310\site-packages\pipenv\utils\processes.py", line 75, in subprocess_run
    return subprocess.run(
  File "C:\Program Files\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
