### ISSUE TITLE
(Discussion) Handling with NoAuthException

### ISSUE THREAD

**Issue by Ken24** [hldh214/lok_bot#66]
After i got this and kept running, my account got banned.

```
2022-05-25 16:MM:SS.ZZZ | DEBUG    | lokbot.client:post:128 - {"url": "field/march/info", "data": {"fromId": "6XXXXXXXXXXXXXXXXX7", "toLoc": [XX, XXX, YYY]}, "elapsed": 0.222473, "res": {"result": false, "err": {"code": "no_auth"}}}
Exception in thread Thread-578 (_handle_eio_message):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/app/.venv/lib/python3.10/site-packages/socketio/client.py", line 621, in _handle_eio_message
    self._handle_event(pkt.namespace, pkt.id, pkt.data)
  File "/app/.venv/lib/python3.10/site-packages/socketio/client.py", line 505, in _handle_event
    r = self._trigger_event(data[0], namespace, *data[1:])
  File "/app/.venv/lib/python3.10/site-packages/socketio/client.py", line 555, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/app/lokbot/farmer.py", line 595, in on_field_objects
    self._on_field_objects_monster(each_obj)
  File "/app/lokbot/farmer.py", line 485, in _on_field_objects_monster
    march_troops = self._prepare_march_troops(each_obj, MARCH_TYPE_MONSTER)
  File "/app/lokbot/farmer.py", line 405, in _prepare_march_troops
    march_info = self.api.field_march_info({
  File "/app/lokbot/client.py", line 575, in field_march_info
    return self.post('field/march/info', data)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 349, in iter
    return fut.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 349, in iter
    return fut.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 349, in iter
    return fut.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 349, in iter
    return fut.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/ratelimit/decorators.py", line 80, in wrapper
    return func(*args, **kargs)
  File "/app/lokbot/client.py", line 140, in post
    raise NoAuthException()
lokbot.exceptions.NoAuthException
```

however, when i could stop running on another account, the account is not banned. So, if NoAuthException occurs, it may be better to stop running.

**Comment by someone21212** [comment]
yes same here i got banned , i created a new account and started the bot and after 10 min it is banned again i think they upgraded there security or something

**Comment by Ken24** [comment]
Hmm, i try with increasing the waiting time a little bit long
https://github.com/hldh214/lok_bot/blob/25484a232c0b1c0782aebf3135d373075c4506fd/lokbot/farmer.py#L601

in addition, i will change and try the
https://github.com/hldh214/lok_bot/blob/25484a232c0b1c0782aebf3135d373075c4506fd/lokbot/farmer.py#L595
to
```
for zone_id in random.sample(zones, min(101, len(zones))-1 )
```

nplus may detect the search where the bot go line by line. therefore, i change the random search (this may be easy to detect from the nplus)

**Comment by someone21212** [comment]
> Hmm, i try with increasing the waiting time a little bit long
> 
> https://github.com/hldh214/lok_bot/blob/25484a232c0b1c0782aebf3135d373075c4506fd/lokbot/farmer.py#L601
> 
> in addition, i will change and try the
> 
> https://github.com/hldh214/lok_bot/blob/25484a232c0b1c0782aebf3135d373075c4506fd/lokbot/farmer.py#L595
> 
> 
> to
> ```
> for zone_id in random.sample(zones, min(101, len(zones))-1 )
> ```
> 
> nplus may detect the search where the bot go line by line. therefore, i change the random search (this may be easy to detect from the nplus)

btw my account that got banned dont have army and no line , i use it just to get the location of the mine so i dont think it have something to do with the line

**Comment by Ken24** [comment]
me too. i don't have army. but, the bot will search the field zone in line by line (like 2131 -> 2132 -> 2133 -> 2141 -> 2142 -> 2143 -> ...)

**Comment by someone21212** [comment]
> me too. i don't have army. but, the bot will search the field zone in line by line (like zone_id: 2131 -> 2132 -> 2133 -> 2141 -> 2142 -> 2143 -> ...)

true , or maybe they just found a way about who is accessing the api and ban them , anyw let me know what happens with u i think u can try on  any new account i was banned in like 10 min

**Comment by Ken24** [comment]
now it seems not banned. maybe nplus was not running bot scan (so not laggy). i continue and watch this work arround.

**Comment by someone21212** [comment]
> now it seems not banned. maybe nplus was not running bot scan (so not laggy). i continue and watch this work arround.

btw did u buyed the 1$ package on the accounts that was banned ? i will try now with buy the 1$ package to see if it will be banned or no

**Comment by Ken24** [comment]
No, i didn't buy in both the current account and banned account. in addition, i experienced that the account where i bought a $9.99 package got banned.

i heard that NPLUS banned package buyer, so many player ask paypal to pay back lol

**Comment by someone21212** [comment]
> No, i didn't buy in both the current account and banned account. in addition, i experienced that the account where i bought a $9.99 package got banned.
> 
> i heard that NPLUS banned package buyer, so many player ask paypal to pay back lol

yes yes i know , but asking maybe they not banning the account that doesnt get reported , i just use it for cmine search and account is only lvl 11 so it is faster than manual search hope it will be fixed so i can use it again let me know if fixed with what u changed

**Comment by goemon161** [comment]
is there a way to not need to connect to the account and choose the coordinates to search for cmine?

**Comment by Ken24** [comment]
I got banned lol. i make an effort to find another work arround

**Comment by someone21212** [comment]
> I got banned lol. i make an effort to find another work arround

as i said i think they found a way to auto ban the account that request api connection

**Comment by someone21212** [comment]
@Ken24 did u find a way or something ?

**Comment by Ken24** [comment]
If only searching fields, then banned right now. if you get baned with `config.example.json`, then you perhaps need to increase `interval` in `socf_thread`. 1min search (which seems massive search) tends to get banned

```
        // Run every 1 minutes.
        "interval": {
          "start": 1,
          "end": 1
        }
```

as for environmental setting, https://help.lords-bot.com/avoiding-bans/ may works as a refference (this is another game bot)

**Comment by Ken24** [comment]
I tried the followings with new casltles

* only run `socf_thread`
* run all tasks in `config.example.json`
* run all tasks except for `socf_thread`

then, at former 2 patterns, i got banned. As for last one, i can keep running ( even though it's only 4-5 hours, but it seems good, i think)

so, something in `socf_thread` (or low-level casle's movement by`socf_thread`) can be checked by nplus

**Comment by Ken24** [comment]
As you may know, current `socf_thread` uses `/field/objects/v2`, but current version of LoK uses  `/field/objects/v3`. NPLUS should detect `v2` and banned hourly at every 0 minutes.

The API `/field/objects/v3` is what they call encrypt API, and in fact the response seems to be encrypted (possibly only compressed). this reverse engineering should take time, but there can be the way to solve because another bot (in telegram) solve this

**Comment by hldh214** [comment]
> 

Thank you for your researching 👍🏻 
I'll try to push a fix later.

**Comment by Ken24** [comment]
thanks. FYI, as for pushing message, it seems `/zone/enter/list/v3`. however, leaving is still `/zone/leave/list/v2`.
