### ISSUE TITLE
Error: Not online

### ISSUE THREAD

**Issue by hunterdaff** [hldh214/lok_bot#7]
The bot is no longer working.Using the last prebuilt image. What could be the problem? Tried to build images myself and other precompiled - the situation is the same everywhere.
```
docker run -e TOKEN=MY_X_ACCESS_TOKEN ghcr.io/hldh214/lok_bot:latest
2022-02-19 11:08:56.492 | DEBUG    | lokbot.client:post:67 - {"url": "kingdom/enter", "data": {}, "res": {"result": true, "kingdom": {"wall": {"fireType": 0, "maxDurability": 5000, "durability": 5000}, "bf": {"status": 0}, "boost": {"total": [[11, 4, 2], [12, 1, 3000], [13, 1, 18000], [21, 1, 100000], [22, 1, 100000], [23, 1, 100000], [24, 1, 100000], [16, 4, 1], [202, 4, 100], [25, 4, 2], [118, 1, 5], [14, 2, 0.01], [29, 1, 7200], [30, 2, 0.1], [31, 2, 0.1], [32, 1, 10], [19, 1, 50000], [20, 1, 100000], [26, 1, 5000], [27, 2, 0.05], [28, 2, 0.05], [87, 2, 0.3], [42, 1, 5], [111, 1, 1], [109, 2, 0.03]]}, "stats": {"battle": {"victory": 0, "defeated": 0, "kill": 0, "death": 0}, "monster": {"attack": 0, "kill": 0}, "economy": {"gathering": 0}, "troops": {"heal": 0, "train": 0}, "alliance": {"donate": 0, "help": 0}, "total": {"crystal": 0, "purchase": 0, "max_purchase": 0, "mint": [], "unmint": [], "medals": 0}}, "vip": {"level": 1, "point": 20, "lastClaimTime": "2022-02-19T02:19:01.597Z"}, "actionPoint": {"value": 150, "lastUpdated": "2022-02-19T02:00:57.106Z"}, "freeChest": {"silver": {"num": 0, "next": "2022-02-19T02:00:56.907Z"}, "gold": {"next": "2022-02-19T02:10:56.907Z"}}, "engage": {"comback": false, "nopay": false}, "option": {"push": 1, "push_war": 1, "alarm": 1, "gift": 1}, "ban": {"face": false, "chat": false}, "klaytn": {"invite": {"card": 3, "total": 0, "res": 0}, "klay": {"claimed": 0, "unclaimed": 0}}, "hospital": {"checking": false, "lastUpdated": "2022-02-19T02:01:16.390Z"}, "deletedInfo": {"loc": []}, "level": 1, "resources": [100000, 100000, 100000, 100000], "crystal": 0, "power": 5510, "worldId": 30, "alliancePoint": 0, "numDonation": 0, "todayHP": 0, "todayRP": 0, "todayDonation": 0, "faceCode": -1, "selectedTreasure": 0, "saveTreasures": [[{"_id": "62104f6c1904db61a5180832", "slot": 0}, {"_id": "62104f6c1904db61a5180833", "slot": 1}], [{"_id": "62104f6dda84c7115b062e28", "slot": 0}, {"_id": "62104f6dda84c7115b062e29", "slot": 1}], [{"_id": "62104f6dda84c7115b062e2a", "slot": 0}, {"_id": "62104f6dda84c7115b062e2b", "slot": 1}], [{"_id": "62104f6dda84c7115b062e2c", "slot": 0}, {"_id": "62104f6dda84c7115b062e2d", "slot": 1}]], "saveTroops": [], "tutorialType": 1, "tutorials": [], "todayLogin": true, "yesterdayLogin": false, "medal": 0, "current_medal": 0, "congressTitle": 0, "mainLandId": 0, "blockIds": [], "_id": "62104f5829f5e74a24c7a42b", "researches": [], "buildings": [{"_id": "62104f6b1904db61a5180819", "position": 1, "code": 40100101, "state": 1, "level": 1, "builded": "2022-02-19T02:01:15.152Z", "lastUpgraded": "2022-02-19T02:01:15.152Z", "lastHarvested": null}, {"_id": "62104f6b1904db61a518081a", "position": 2, "code": 40100102, "state": 1, "level": 1, "builded": "2022-02-19T02:01:15.304Z", "lastUpgraded": "2022-02-19T02:01:15.304Z", "lastHarvested": null}, {"_id": "62104f6b1904db61a518081b", "position": 3, "code": 40100103, "state": 1, "level": 1, "builded": "2022-02-19T02:01:15.367Z", "lastUpgraded": "2022-02-19T02:01:15.367Z", "lastHarvested": null}, {"_id": "62104f6b1904db61a518081c", "position": 4, "code": 40100104, "state": 1, "level": 1, "builded": "2022-02-19T02:01:15.498Z", "lastUpgraded": "2022-02-19T02:01:15.498Z", "lastHarvested": null}, {"_id": "62104f6b1904db61a518081d", "position": 5, "code": 40100105, "state": 1, "level": 1, "builded": "2022-02-19T02:01:15.619Z", "lastUpgraded": "2022-02-19T02:01:15.619Z", "lastHarvested": null}, {"_id": "62104f6b1904db61a518081e", "position": 6, "code": 40100106, "state": 1, "level": 1, "builded": "2022-02-19T02:01:15.783Z", "lastUpgraded": "2022-02-19T02:01:15.783Z", "lastHarvested": "2022-02-19T02:01:16.390Z", "param": {"wounded": [], "cured": []}}, {"_id": "62104f6b1904db61a518081f", "position": 7, "code": 40100107, "state": 1, "level": 1, "builded": "2022-02-19T02:01:15.947Z", "lastUpgraded": "2022-02-19T02:01:15.947Z", "lastHarvested": null}, {"_id": "62104f6c1904db61a5180820", "position": 8, "code": 40100108, "state": 1, "level": 1, "builded": "2022-02-19T02:01:16.077Z", "lastUpgraded": "2022-02-19T02:01:16.077Z", "lastHarvested": null}, {"_id": "62104f6c1904db61a5180821", "position": 9, "code": 40100109, "state": 1, "level": 1, "builded": "2022-02-19T02:01:16.198Z", "lastUpgraded": "2022-02-19T02:01:16.198Z", "lastHarvested": null}], "troops": [], "supports": [], "lastDonationCheckTime": "2022-02-19T02:00:56.887Z", "treasure": [{"_id": "62104f6c1904db61a5180832", "slot": 0}, {"_id": "62104f6c1904db61a5180833", "slot": 1}], "bookmarks": [], "registered": "2022-02-19T02:00:56.887Z", "skills": [], "userId": "62104f5829f5e74a24c7a42a", "name": "ponomarev6y991", "__v": 0, "fieldObjectId": "62104f5929f5e74a24c7a42d", "lastLogined": "2022-02-19T02:30:03.428Z", "numSeriesLogin": 1, "lordId": "62104f6c1904db61a5180822", "connectedSocketId": "", "logined": false, "loc": [30, 441, 1861], "lord": {"level": 1, "xp": 0, "point": 1}, "logging": false}, "dbTime": "2022-02-19T03:08:56.421Z", "blockIds": [], "captcha": null, "networks": {"api": "https://api-lok-live.leagueofkingdoms.com/api", "kingdoms": ["https://sock-lok-live.leagueofkingdoms.com/socket.io/"], "fields": ["https://socf-lok-live.leagueofkingdoms.com/socket.io/"], "chats": ["https://socc-lok-live.leagueofkingdoms.com/socket.io/"]}}, "elapsed": 0.807076}
2022-02-19 11:08:58.803 | DEBUG    | lokbot.client:post:67 - {"url": "alliance/help/all", "data": {}, "res": {"result": false, "err": {"code": "no_alliance"}}, "elapsed": 0.306764}
2022-02-19 11:09:01.127 | DEBUG    | lokbot.client:post:67 - {"url": "kingdom/vip/info", "data": {}, "res": {"result": true, "vip": {"level": 1, "point": 20, "nextRewardDate": "2022-02-20T00:00:00.000Z", "isClaimed": true}}, "elapsed": 0.319511}
2022-02-19 11:09:03.433 | DEBUG    | lokbot.client:post:67 - {"url": "item/list", "data": {}, "res": {"result": true, "items": [{"code": 10101015, "amount": 1, "level": 0, "_id": "62105395b4d88c7e5d949f5b"}, {"code": 10101024, "amount": 1, "level": 0, "_id": "62105395b4d88c7e5d94a3eb"}, {"code": 10101033, "amount": 1, "level": 0, "_id": "62105395b4d88c7e5d94a853"}, {"code": 10101050, "amount": 1, "level": 0, "_id": "62105395b4d88c7e5d94ad93"}, {"code": 10104002, "amount": 1, "level": 0, "_id": "62104f58b4d88c7e5dbab071"}, {"code": 10104030, "amount": 1, "level": 0, "_id": "62104f58b4d88c7e5dbab05f"}, {"code": 10104091, "amount": 1, "level": 0, "_id": "62104f58b4d88c7e5dbab07a"}, {"code": 10104129, "amount": 1, "level": 0, "_id": "62104f58b4d88c7e5dbab081"}]}, "elapsed": 0.303155}
2022-02-19 11:09:05.755 | DEBUG    | lokbot.client:post:67 - {"url": "item/use", "data": {"code": 10101015, "amount": 1}, "res": {"result": false, "err": {"code": "not_online"}}, "elapsed": 0.317423}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/lokbot/__main__.py", line 5, in <module>
    fire.Fire(main)
  File "/app/.venv/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/app/.venv/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/app/.venv/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/app/lokbot/app.py", line 31, in main
    schedule.run_all()
  File "/app/.venv/lib/python3.10/site-packages/schedule/__init__.py", line 787, in run_all
    default_scheduler.run_all(delay_seconds=delay_seconds)
  File "/app/.venv/lib/python3.10/site-packages/schedule/__init__.py", line 118, in run_all
    self._run_job(job)
  File "/app/.venv/lib/python3.10/site-packages/schedule/__init__.py", line 172, in _run_job
    ret = job.run()
  File "/app/.venv/lib/python3.10/site-packages/schedule/__init__.py", line 661, in run
    ret = self.job_func()
  File "/app/lokbot/farmer.py", line 774, in use_resource_in_item_list
    self.api.item_use(each_item.get('code'), each_item.get('amount'))
  File "/app/lokbot/client.py", line 312, in item_use
    return self.post('item/use', {'code': code, 'amount': amount})
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 349, in iter
    return fut.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 349, in iter
    return fut.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 349, in iter
    return fut.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 349, in iter
    return fut.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/ratelimit/decorators.py", line 80, in wrapper
    return func(*args, **kargs)
  File "/app/lokbot/client.py", line 100, in post
    raise OtherException(code)
lokbot.exceptions.OtherException: not_online
```

**Comment by iPowerLife** [comment]
by the way yes, errors with offline
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/ratelimit/decorators.py", line 80, in wrapper
    return func(*args, **kargs)
  File "/app/lokbot/client.py", line 100, in post
    raise OtherException(code)
lokbot.exceptions.OtherException: not_online

**Comment by iPowerLife** [comment]
when is the fix expected?
    result = fn(*args, **kwargs)

  File "/app/.venv/lib/python3.10/site-packages/ratelimit/decorators.py", line 80, in wrapper

    return func(*args, **kargs)

  File "/app/lokbot/client.py", line 100, in post

    raise OtherException(code)

**lokbot.exceptions.OtherException: not_online**

**Comment by iPowerLife** [comment]
![image](https://user-images.githubusercontent.com/99628430/155254761-dea9de9f-5777-4b94-850b-4a1c417b0200.png)

**Comment by hldh214** [comment]
> ![image](https://user-images.githubusercontent.com/99628430/155254761-dea9de9f-5777-4b94-850b-4a1c417b0200.png)

Did you try the latest commit https://github.com/hldh214/lok_bot/commit/72fc776ce3c1945f7de766a24039400c88c68220? Which can detect `not_online` and make another request trying to solve it.

**Comment by iPowerLife** [comment]
> > ![изображение](https://user-images.githubusercontent.com/99628430/155254761-dea9de9f-5777-4b94-850b-4a1c417b0200.png)
> 
> Вы пробовали последний коммит [72fc776](https://github.com/hldh214/lok_bot/commit/72fc776ce3c1945f7de766a24039400c88c68220) ? Который может `not_online`решить эту проблему.

I do not quite understand you)

**Comment by iPowerLife** [comment]
![image](https://user-images.githubusercontent.com/99628430/155495279-a9ccc6cd-9336-409a-a232-812048aa4c70.png)
here is an error

**Comment by iPowerLife** [comment]
![image](https://user-images.githubusercontent.com/99628430/155495447-604d7b9a-c2ee-45a7-8026-02820ad208f6.png)

**Comment by hldh214** [comment]
Please try this 7de35908846344320db46a032ee493ce7fae0d7c
And make sure close your browser before launch bot.

**Comment by mohsenyzd10** [comment]
> @iPowerLife Hi, does this issue still exist? @mohsenyzd10 also faced this and maybe we need some more investigation.

the new changes make it worse I got many errors 

![image](https://user-images.githubusercontent.com/91246296/155730613-89de58cd-b89a-4b39-b4df-057751dd7235.png)

**Comment by iPowerLife** [comment]
> @iPowerLife Привет, эта проблема все еще существует? @mohsenyzd10 тоже столкнулся с этим, и, возможно, нам нужно провести дополнительное расследование.

нет, все хорошо за 1 день бот в принципе сделал 10 уровень и по 2 миллиона ресурса получилось, я успел его ограбить основным аккаунтом, как после аккаунт заблокировали) но иногда приходится руками что то делать, бот не всегда стабилен и быстрый, как я это сделаю руками. Например я не увидел, чтобы бот сам строил и повышал уровни шахт и строил дополнительные шахты и их так же повышал. Я только вижу что навыки прокачивает и все. Награды он тоже не собирает кстати.

**Comment by divsriv111** [comment]
any for this? I am still getting "not_online" error

**Comment by hldh214** [comment]
> any fix this? I am still getting "not_online" error

Since I cannot reproduce it, no.
And a command line output will be useful for us to take a further investigate.

**Comment by mohsenyzd10** [comment]
![image](https://user-images.githubusercontent.com/91246296/156721159-4b906e89-9e51-45f7-8840-80eeedccbc86.png)

**Comment by mohsenyzd10** [comment]
![image](https://user-images.githubusercontent.com/91246296/156752998-2c617fd7-5b37-416a-be78-f8d61e432fb9.png)
![image](https://user-images.githubusercontent.com/91246296/156753082-0fead308-4872-45a0-8fca-47638dc7f62d.png)

**Comment by mohsenyzd10** [comment]
it's seems working, good job.
thank you

**Comment by mikhi-nde** [comment]
hi all.
just wanted to note that the error "not online" exists even in the browser. i have seen it.

**Comment by hldh214** [comment]
> hi all. just wanted to note that the error "not online" exists even in the browser. i have seen it.

Yea... They are promoting mobile apps. https://github.com/hldh214/lok_bot/issues/7#issuecomment-1045783522

**Comment by mohsenyzd10** [comment]
the not online error get worse since server of the game are awful and we have lag , every time I should login again and get new access token.
is there possible that we have login option in bot (give bot our user pass), so but could get new access token by himself !

**Comment by hldh214** [comment]
> is there possible that we have login option in bot (give bot our user pass), so bot could get new access token by himself !

Login by email&password would be easy to implement, but OAuth method(Google, Apple, ...) would be hard IMHO, and that's my consideration why we still using `x-access-token`.

**Comment by himhhm** [comment]
When I restart the bot with the same x-access-token the bot will be work again. So is there a way to do like restart the bot when "not_online" error occurred automatically?

**Comment by hldh214** [comment]
> So is there a way to do like restart the bot when "not_online" error occurred automatically?

I'm using docker container with [autoheal](https://github.com/willfarrell/docker-autoheal) to auto-restart on exception.
