### ISSUE TITLE
getting the ff error please help

### ISSUE THREAD

**Issue by ragnakistah** [hldh214/lok_bot#76]
2022-07-03 23:57:09.974 | DEBUG    | lokbot.client:post:129 - {"url": "kingdom/enter", "data": {}, "elapsed": 1.712168, "res": {"result": false, "err": {"code": "duplicated"}}}
2022-07-03 23:57:12.510 | DEBUG    | lokbot.client:post:129 - {"url": "kingdom/enter", "data": {}, "elapsed": 0.520126, "res": {"result": false, "err": {"code": "duplicated"}}}
2022-07-03 23:57:15.207 | DEBUG    | lokbot.client:post:129 - {"url": "kingdom/enter", "data": {}, "elapsed": 0.673689, "res": {"result": false, "err": {"code": "duplicated"}}}
2022-07-03 23:57:17.815 | DEBUG    | lokbot.client:post:129 - {"url": "kingdom/enter", "data": {}, "elapsed": 0.595396, "res": {"result": false, "err": {"code": "duplicated"}}}
Traceback (most recent call last):
  File "C:\Users\131698\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\131698\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\131698\Downloads\lok_bot-1.9.0\lokbot\__main__.py", line 5, in <module>
    fire.Fire(main)
  File "C:\Users\131698\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\131698\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\131698\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\131698\Downloads\lok_bot-1.9.0\lokbot\app.py", line 69, in main
    farmer = LokFarmer(token, captcha_solver_config)
  File "C:\Users\131698\Downloads\lok_bot-1.9.0\lokbot\farmer.py", line 74, in __init__
    self.kingdom_enter = self.api.kingdom_enter()
  File "C:\Users\131698\Downloads\lok_bot-1.9.0\lokbot\client.py", line 330, in kingdom_enter
    res = self.post('kingdom/enter')
  File "C:\Users\131698\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity\__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\131698\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity\__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\131698\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity\__init__.py", line 349, in iter
    return fut.result()
  File "C:\Users\131698\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\131698\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\131698\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity\__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\131698\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity\__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\131698\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity\__init__.py", line 414, in __call__
    self.sleep(do)
  File "C:\Users\131698\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity\nap.py", line 31, in sleep
    time.sleep(seconds)

**Comment by lephuoccan** [comment]
The Api has been changed and encrypted, new version of bot may not be finalized and public

**Comment by ragnakistah** [comment]
ohhh gotcha i thought im doing something wrong will wait for the new release

**Comment by CloudBotScripts** [comment]
You should try lok.cloudbot.site, it is working with encryption as it uses image recognition instead of the API.

**Comment by RHearNaJa** [comment]
same problem
